spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    check-template: true
    check-template-location: true

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.107.91.8:3306/okz?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      username: okz
      password: okz123!@#
      initial-size: 10
      max-active: 20
      validation-query: select 'X'
      test-on-borrow: true

  redis:
      database: 0
      password:
      cluster:
        nodes:
         - 39.107.91.8:8001
         - 39.107.91.8:8002
         - 39.107.91.8:8000
      lettuce:
        pool:
          max-active: 3
          max-idle: 1
          min-idle: 1
          max-wait: 1000
      timeout: 1000
